package io.kritrimabuddhi.codegen.openapi2mcp.generator

import io.kritrimabuddhi.codegen.openapi2mcp.cli.CliOptions
import io.kritrimabuddhi.codegen.openapi2mcp.parser.model.ParsedOpenApi
import jakarta.enterprise.context.ApplicationScoped
import jakarta.inject.Inject
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

/**
 * Main orchestrator for code generation.
 *
 * Coordinates all generators to produce a complete Quarkus-based SDK
 * from a parsed OpenAPI specification.
 */
@ApplicationScoped
class CodeGenerator {

  @Inject
  private lateinit var domainGenerator: DomainGenerator

  @Inject
  private lateinit var clientGenerator: ClientGenerator

  @Inject
  private lateinit var toolGenerator: ToolGenerator

  /**
   * Generate all code artifacts from the parsed OpenAPI specification.
   *
   * @param parsedApi The parsed OpenAPI specification
   * @param options CLI options with output directory and package information
   */
  fun generate(parsedApi: ParsedOpenApi, options: CliOptions) {
    // Create main output directory structure
    createDirectoryStructure(options.output)

    // Generate domain layer
    domainGenerator.generate(options, parsedApi.schemas)

    // Generate client layer
    clientGenerator.generate(options, parsedApi.paths, parsedApi.info)

    // Generate MCP tool layer
    toolGenerator.generate(options, parsedApi.paths, parsedApi.info)

    // Generate application configuration
    generateApplicationConfig(options, parsedApi)
  }

  private fun createDirectoryStructure(outputDir: Path) {
    val dirsToCreate = listOf(
      outputDir.resolve("src/main/kotlin"),
      outputDir.resolve("src/main/resources"),
      outputDir.resolve("src/test/kotlin"),
      outputDir.resolve("src/test/resources")
    )

    dirsToCreate.forEach { dir ->
      if (!java.nio.file.Files.exists(dir)) {
        dir.createDirectories()
      }
    }
  }

  private fun generateApplicationConfig(options: CliOptions, parsedApi: ParsedOpenApi) {
    val configContent = generateApplicationConfigContent(options, parsedApi)
    val configPath = options.output.resolve("src/main/resources/application.properties")
    configPath.writeText(configContent)
  }

  private fun generateApplicationConfigContent(options: CliOptions, parsedApi: ParsedOpenApi): String {
    val configKey = options.configKey
    val baseUrl = extractBaseUrl(parsedApi)
    val title = parsedApi.info.title.lowercase().replace(" ", "-")

    return """
# Quarkus application configuration for ${parsedApi.info.title}
# Generated by OpenAPI to MCP Generator

# REST Client configuration for $configKey
${configKey}/url=${baseUrl}
${configKey}/scope=${options.rootPackage}

# Default configuration
quarkus.application.name=${title}
quarkus.http.port=8080
quarkus.log.level=INFO

# LangChain4j configuration
quarkus.langchain4j.enabled=true
        """.trimIndent()
  }

  private fun extractBaseUrl(parsedApi: ParsedOpenApi): String {
    // Try to extract base URL from OpenAPI servers
    // Default to localhost for demo purposes
    // In production, this should be configured via environment or properties
    return "http://localhost:8080"
  }
}